//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kiltex.SistemaGestion.Services.Scripts {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlScripts() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kiltex.SistemaGestion.Services.Scripts.SqlScripts", typeof(SqlScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a   SELECT TOP(1) B.id, B.description FROM [brand] B
        ///  INNER JOIN [product] P
        ///  ON P.brand_id = B.id
        ///  WHERE B.id = @brandid
        ///  AND P.[is_deleted] = 0.
        /// </summary>
        internal static string GetBrandById {
            get {
                return ResourceManager.GetString("GetBrandById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a   SELECT TOP(1) * FROM [category] C
        ///  INNER JOIN [product] P
        ///  ON P.[category_id] = C.id
        ///  WHERE C.id = @categoryid
        ///  AND P.[is_deleted] = 0.
        /// </summary>
        internal static string GetCategoryById {
            get {
                return ResourceManager.GetString("GetCategoryById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  SELECT TOP(1) * FROM [product] P
        ///  
        ///  WHERE P.id = @productid.
        /// </summary>
        internal static string GetProductById {
            get {
                return ResourceManager.GetString("GetProductById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT	[p].[id], 
        ///		[p].[description], 
        ///		[p].[code], 
        ///		[B].[description] AS [brandName], 
        ///		[p].[quantity],
        ///		[p].[purchase_price],
        ///		CONVERT (DECIMAL(18,2), ([p].[quantity] * [p].[purchase_price])) AS [subTotal]
        ///
        ///FROM [product] [p] 
        ///
        ///JOIN [brand] [B]
        ///ON [B].[id] = [p].[brand_id]
        ///
        ///WHERE [quantity] &gt; 0 AND [is_deleted] = 0
        ///ORDER BY [p].[description].
        /// </summary>
        internal static string GetProductReport {
            get {
                return ResourceManager.GetString("GetProductReport", resourceCulture);
            }
        }
    }
}
