USE [Ordbox]
 IF NOT EXISTS (
 SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE INFORMATION_SCHEMA.COLUMNS.TABLE_NAME = N'BUDGET' AND INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME = N'is_inactive'
 )
 BEGIN
 ALTER TABLE [budget] ADD [is_inactive] BIT NOT NULL default (0) 
 END
 GO

  IF NOT EXISTS (
 SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE INFORMATION_SCHEMA.COLUMNS.TABLE_NAME = N'RECEIPT' AND INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME = N'is_inactive'
 )
 BEGIN
 ALTER TABLE [receipt] ADD [is_inactive] BIT NOT NULL default (0) 
 END
 GO
