USE [Ordbox]
 IF NOT EXISTS (
 SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE INFORMATION_SCHEMA.COLUMNS.TABLE_NAME = N'INVOICE' AND INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME = N'cae'
 )
 BEGIN
 ALTER TABLE [invoice] ADD [cae] NVARCHAR(200) NULL 
 END
 GO
