USE [Ordbox]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = N'dbo' AND TABLE_NAME = N'integration_log_invoice')

BEGIN
	CREATE TABLE [dbo].[integration_log_invoice](
		[id] [bigint] IDENTITY(1,1) NOT NULL,
		[invoice_id] [bigint] NULL,
		[request] NVARCHAR(MAX) NULL,
		[response] NVARCHAR(MAX) NULL,
		[endpoint] NVARCHAR(255) NULL,
		[success] [BIT] NOT NULL,
		[created_on] DATETIMEOFFSET NOT NULL
	 CONSTRAINT [PK_integration_log_invoice] PRIMARY KEY CLUSTERED 
	(
		[id] ASC
	)WITH (PAD_INDEX = OFF, 
	STATISTICS_NORECOMPUTE = OFF, 
	IGNORE_DUP_KEY = OFF, 
	ALLOW_ROW_LOCKS = ON, 
	ALLOW_PAGE_LOCKS = ON,
	OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF
	) ON [PRIMARY]
	) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

END
GO
