USE [Ordbox]
 IF NOT EXISTS (
 SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE INFORMATION_SCHEMA.COLUMNS.TABLE_NAME = N'DEBIT_MEMO' AND INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME = N'cae'
 )
 BEGIN
 ALTER TABLE [debit_memo] ADD [cae] NVARCHAR(200) NULL 
 END

 IF NOT EXISTS (
 SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE INFORMATION_SCHEMA.COLUMNS.TABLE_NAME = N'DEBIT_MEMO' AND INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME = N'cae_expiration_date'
 )
 BEGIN
 ALTER TABLE [debit_memo] ADD [cae_expiration_date] DateTime NULL 
 END

 IF NOT EXISTS (
 SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE INFORMATION_SCHEMA.COLUMNS.TABLE_NAME = N'DEBIT_MEMO' AND INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME = N'integration_success'
 )
 BEGIN
 ALTER TABLE [debit_memo] ADD [integration_success] BIT NULL 
 END

 IF NOT EXISTS (
 SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE INFORMATION_SCHEMA.COLUMNS.TABLE_NAME = N'DEBIT_MEMO' AND INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME = N'version'
 )
 BEGIN
 ALTER TABLE [debit_memo] ADD [version] TINYINT NOT NULL
 CONSTRAINT DF_debit_memo_version DEFAULT (0);
 END

 GO
